# Generated by Django 6.0.3 on 2026-06-11 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0002_alter_secretaria_options_ayuda'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='secretarias.secretaria')),
            ],
            options={
                'ordering': ['nombre'],
                'unique_together': {('secretaria', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.oficina'),
        ),
    ]
