# Generated by Django 6.0.3 on 2026-06-11 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0003_oficina'),
        ('usuarios', '0002_oficina_perfilusuario_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='oficina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='secretarias.oficina'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='es_admin_area',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Oficina',
        ),
    ]
