BARRIOS = [
    "2 de Abril",
    "3 de Abril",
    "35 viviendas",
    "490 Norte",
    "490 Sur",
    "711 Lotes",
    "Aldea Casablanca",
    "Área 11",
    "Área 12",
    "Área 12 - Loteo Social",
    "Área 13",
    "Área 16 - Barranco",
    "Área 16 - Juan Manuel de Rosas",
    "Centro",
    "Chacra 5",
    "Chacra 8",
    "Chacra 9",
    "Comercio I",
    "Comercio II",
    "Covipa",
    "Covira",
    "Docente",
    "Fitipaldi",
    "General Valle",
    "Gregorio Mayo",
    "Hunt",
    "I.A.C.",
    "I.A.C. - 12 Apostoles",
    "La Isla",
    "Los Hornitos",
    "Los Pinos",
    "Lotear",
    "Luis Vernet",
    "Madre Solas",
    "Playa Cangrejales - El Faro",
    "Playa Magagna - Bonita",
    "Playa Unión",
    "Policial",
    "Puerto",
    "Río Chubut",
    "Roca",
    "Rodaj Park",
    "Ruta 25",
    "Ruta 7",
    "San Pablo",
    "San Ramón",
    "Seros",
    "Tiro Federal",
    "Unidad 6",
    "U.P.C.N.",
]

BARRIOS_CHOICES = [(b, b) for b in BARRIOS]