# Generated by Django 6.0.3 on 2026-03-13 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretaria',
            options={'ordering': ['nombre'], 'verbose_name': 'Secretaria', 'verbose_name_plural': 'Secretarias'},
        ),
        migrations.CreateModel(
            name='Ayuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activa', models.BooleanField(default=True)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ayudas', to='secretarias.secretaria')),
            ],
            options={
                'verbose_name': 'Ayuda',
                'verbose_name_plural': 'Ayudas',
                'ordering': ['secretaria__nombre', 'nombre'],
                'unique_together': {('secretaria', 'nombre')},
            },
        ),
    ]
