# Generated by Django 5.2.15 on 2026-07-01 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0003_oficina'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_remitente', models.CharField(help_text='Nombre que verá el destinatario.', max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('usar_tls', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('secretaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_correo', to='secretarias.secretaria')),
            ],
            options={
                'verbose_name': 'Configuración de correo',
                'verbose_name_plural': 'Configuraciones de correo',
            },
        ),
    ]
