# Generated by Django 6.0.3 on 2026-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secretarias', '0004_configuracioncorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='nombre_remitente',
            field=models.CharField(blank=True, help_text='Nombre que verá el destinatario.', max_length=150),
        ),
        migrations.AlterField(
            model_name='configuracioncorreo',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
