# Generated by Django 6.0.3 on 2026-03-27 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0001_initial'),
        ('secretarias', '0002_alter_secretaria_options_ayuda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('OTORGADA', 'Otorgada'), ('RECHAZADA', 'Rechazada')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretarias.ayuda')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='personas.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de ayuda',
                'verbose_name_plural': 'Solicitudes de ayuda',
                'ordering': ['-fecha'],
            },
        ),
    ]
