# Generated by Django 6.0.3 on 2026-03-31 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
        ('secretarias', '0002_alter_secretaria_options_ayuda'),
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntregaAyuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True)),
                ('ayuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='secretarias.ayuda')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='personas.persona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrega de ayuda',
                'verbose_name_plural': 'Entregas de ayuda',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntregaAyudaConviviente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('parentesco', models.CharField(blank=True, max_length=50)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convivientes_relacionados', to='solicitudes.entregaayuda')),
            ],
            options={
                'verbose_name': 'Conviviente relacionado',
                'verbose_name_plural': 'Convivientes relacionados',
            },
        ),
        migrations.DeleteModel(
            name='SolicitudAyuda',
        ),
    ]
