# Generated by Django 6.0.3 on 2026-07-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_entregaayuda_entregaayudaconviviente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregaayuda',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregaayuda',
            name='error_envio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entregaayuda',
            name='fecha_envio_email',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregaayuda',
            name='numero_recibo',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número de recibo'),
        ),
        migrations.AddField(
            model_name='entregaayuda',
            name='pdf_recibo',
            field=models.FileField(blank=True, null=True, upload_to='recibos/', verbose_name='Comprobante PDF'),
        ),
    ]
