# Generated by Django 6.0.3 on 2026-06-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='encuesta_social_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
